name: "Terraform CI/CD Pipeline"

# Trigger the pipeline when code is pushed to the main branch
# or when you manually click the "Run workflow" button
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  terraform-infrastructure:
    name: "Deploy AWS Infrastructure"
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download your repository code onto the GitHub server
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Authenticate with AWS securely using GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Install the latest version of Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Step 4: Initialize Terraform (Downloads providers)
      - name: Terraform Init
        run: terraform init

      # Step 5: Check the code for formatting errors
      - name: Terraform Format Check
        run: terraform fmt -check

      # Step 6: Preview the changes
      - name: Terraform Plan
        run: terraform plan

      # Step 7: Build the infrastructure automatically!
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve